### ISSUE TITLE
Showing the data from at least one API call

### ISSUE THREAD

**Issue by arifjehoh** [arifjehoh/bored-activity#19]

**Comment by arifjehoh** [comment]
# Bored API
[Here is the link to the API](https://www.boredapi.com/)

**Comment by arifjehoh** [comment]
We could aim for learning how to fetch a single activity and show it the screen, into a *card* which have all the data.

**Comment by arifjehoh** [comment]
We could also do a firebase connection where we have the single activity added to the firebase, just saving it, doesn't need to be more then that. It will change when we start working on the project.

**Comment by Abdullahtr249** [comment]
Abdullahtr249/issue/19


#19: feat: Created a new component "ActivityList"
#19: add:  added a new component "ActivityList" to App.vue

**Comment by Abdullahtr249** [comment]
Abdullahtr249/issue/19


#19: fix: updated  'src/App.vue'
